#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms

yum_install java-1.8.0-openjdk-devel unzip

http_proxy=$PROXY curl -sO http://www.mirrorservice.org/sites/ftp.apache.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -xzf apache-maven-3.3.9-bin.tar.gz
mv apache-maven-3.3.9 /usr/local
ln -sf /usr/local/apache-maven-3.3.9/bin/mvn /usr/local/bin

mkdir -p /home/demo/.m2
cp settings.xml /home/demo/.m2
chown -R demo:demo /home/demo/.m2

### Download and install JBDS
# http://download.eng.brq.redhat.com/released/jbdevstudio/8.1.0/jboss-devstudio-8.1.0.GA-installer-standalone.jar
curl -sO http://$APILISTENER/static/isos/jboss-devstudio-8.1.0.GA-installer-standalone.jar
java -jar jboss-devstudio-8.1.0.GA-installer-standalone.jar InstallConfigRecord.xml
cp 'Red Hat JBoss Developer Studio 8.1.0.GA.desktop' /usr/share/applications
install -m 0755 -o demo 'Red Hat JBoss Developer Studio 8.1.0.GA.desktop' /home/demo/Desktop

### Install Integration Stack
/usr/local/jbdevstudio/jbdevstudio -p2.os linux -application org.eclipse.equinox.p2.director -repository https://devstudio.redhat.com/earlyaccess/8.0/ -installIU org.fusesource.ide.camel.editor.feature.feature.group,org.fusesource.ide.core.feature.feature.group,org.fusesource.ide.fabric8.feature.feature.group,org.fusesource.ide.jmx.feature.feature.group,org.fusesource.ide.server.extensions.feature.feature.group,org.jboss.tools.fuse.transformation.feature.feature.group

### Download and install Fuse
FUSE_PATH="/home/demo/fuse"
# http://download.eng.brq.redhat.com/released/JBossFuse/6.2.1/jboss-fuse-full-6.2.1.redhat-084.zip
curl -sO http://$APILISTENER/static/isos/jboss-fuse-full-6.2.1.redhat-084.zip
unzip -q jboss-fuse-full-6.2.1.redhat-084.zip
mv jboss-fuse-6.2.1.redhat-084 $FUSE_PATH
sed -i -e 's/^#admin=/admin=/' $FUSE_PATH/etc/users.properties

JAVA_HOME=/usr/lib/jvm/java-1.8.0 $FUSE_PATH/bin/start
while ! $FUSE_PATH/bin/client </dev/null &>/dev/null; do
  sleep 10
done

$FUSE_PATH/bin/client <<EOF
features:install wrapper
wrapper:install -n fuse
EOF

$FUSE_PATH/bin/client <<EOF
osgi:shutdown -f
EOF

for ((i = 0; i < 6; i++)); do
  if [ -z "$(pidof java)" ]; then
    break
  fi
  if [ $i -lt 5 ]; then
    sleep 10
  else
    false
  fi
done

sed -i -e 's/^#RUN_AS_USER=/RUN_AS_USER=demo/' $FUSE_PATH/bin/fuse-service
chown -R demo:demo $FUSE_PATH

ln -s $FUSE_PATH/bin/fuse-service /etc/init.d
chkconfig --add fuse-service
chkconfig fuse-service on
service fuse-service start

for ((i = 0; i < 30; i++)); do
  if $FUSE_PATH/bin/client </dev/null &>/dev/null; then
    break
  fi
  if [ $i -lt 29 ]; then
    sleep 10
  else
    false
  fi
done

$FUSE_PATH/bin/client <<EOF
fabric:create --clean --wait-for-provisioning -m 127.0.0.1 -g manualip -r manualip
EOF

for ((i = 0; i < 30; i++)); do
  if $FUSE_PATH/bin/client </dev/null &>/dev/null; then
    break
  fi
  if [ $i -lt 29 ]; then
    sleep 10
  else
    false
  fi
done

$FUSE_PATH/bin/client <<EOF
fabric:container-create-child --profile example-camel-loanbroker-mq.loanBroker root loanbroker
fabric:container-create-child --profile example-camel-loanbroker-mq.bank1 root bank1
fabric:container-create-child --profile example-camel-loanbroker-mq.bank2 root bank2
fabric:container-create-child --profile example-camel-loanbroker-mq.bank3 root bank3
EOF

firefox_set_homepage http://localhost:8181/
