#!/bin/bash -e

. utils/functions

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

BASE=$1
TARGET=${BASE//\//:}

if [ -e layers/$BASE/properties ]; then
  . layers/$BASE/properties
fi

export MEM=${MEM:-1024}
export NAME=${NAME:-$TARGET}
export CPUS=${CPUS:-1}

if [ -e build/rhev/$TARGET.ova ]; then
  echo "$0: build/rhev/$TARGET.ova already exists, not rebuilding"
  exit
fi

utils/addlayer.sh build/$TARGET.qcow2 targets/rhev tmp/$TARGET:rhev.qcow2
convert_qcow2 tmp/$TARGET:rhev.qcow2 qcow2

TMPDIR=$(mktemp -d)

export IMAGE_UUID=$(uuidgen)
export DISK_UUID=$(uuidgen)
export TEMPLATE_UUID=$(uuidgen)
export NIC_UUID=$(uuidgen)

export UUID_1=$(uuidgen)
export UUID_2=$(uuidgen)
export UUID_3=$(uuidgen)
export UUID_4=$(uuidgen)
export UUID_5=$(uuidgen)

export DATE_S=$(date +%s)
export DATE_YMDHMS=$(date -u +'%Y/%m/%d %H:%M:%S')
export SECTORS=$((20*1024**3/512))

mkdir -p $TMPDIR/{images/$IMAGE_UUID,master/vms/$TEMPLATE_UUID}

envsubst <$(dirname $0)/disk.meta >$TMPDIR/images/$IMAGE_UUID/$DISK_UUID.meta
envsubst <$(dirname $0)/template.ovf >$TMPDIR/master/vms/$TEMPLATE_UUID/$TEMPLATE_UUID.ovf

tar -Pczf tmp/$TARGET.ova --transform="s!$TMPDIR/!!" --transform="s!tmp/$TARGET:rhev.qcow2!images/$IMAGE_UUID/$DISK_UUID!" $TMPDIR/master/vms/$TEMPLATE_UUID/$TEMPLATE_UUID.ovf $TMPDIR/images/$IMAGE_UUID/$DISK_UUID.meta tmp/$TARGET:rhev.qcow2
rm -rf tmp/$TARGET:rhev.qcow2 $TMPDIR

mkdir -p build/rhev
mv tmp/$TARGET.ova build/rhev/$TARGET.ova
