#!/bin/bash -e

. utils/functions

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

BASE=$1
TARGET=$(basename $(dirname $0))

read_config $BASE $TARGET

export BASE

utils/addlayer.sh build/$BASE.qcow2 targets/$TARGET tmp/$BASE:$TARGET.qcow2
convert_qcow2 tmp/$BASE:$TARGET.qcow2 qcow2

TMPDIR=$(mktemp -d)

export IMAGE_UUID=$(uuidgen)
export DISK_UUID=$(uuidgen)
export TEMPLATE_UUID=$(uuidgen)
export NIC_UUID=$(uuidgen)

export UUID_1=$(uuidgen)
export UUID_2=$(uuidgen)
export UUID_3=$(uuidgen)
export UUID_4=$(uuidgen)
export UUID_5=$(uuidgen)

export DATE_S=$(date +%s)
export DATE_YMDHMS=$(date -u +'%Y/%m/%d %H:%M:%S')
export SECTORS=$((DISK*2**30/512))

mkdir -p $TMPDIR/{images/$IMAGE_UUID,master/vms/$TEMPLATE_UUID}

envsubst <targets/$TARGET/disk.meta >$TMPDIR/images/$IMAGE_UUID/$DISK_UUID.meta
envsubst <targets/$TARGET/template.ovf >$TMPDIR/master/vms/$TEMPLATE_UUID/$TEMPLATE_UUID.ovf

tar -Pczf tmp/$BASE:$TARGET.ova --transform="s!$TMPDIR/!!" --transform="s!tmp/$BASE:$TARGET.qcow2!images/$IMAGE_UUID/$DISK_UUID!" $TMPDIR/master/vms/$TEMPLATE_UUID/$TEMPLATE_UUID.ovf $TMPDIR/images/$IMAGE_UUID/$DISK_UUID.meta tmp/$BASE:$TARGET.qcow2
rm -rf tmp/$BASE:$TARGET.qcow2 $TMPDIR

mv tmp/$BASE:$TARGET.ova releases/$BASE:$TARGET.ova
