#!/bin/bash -e

. utils/functions

TARGET=$1:$(basename $(dirname $0))

. targets/$TARGET

if [ -e build/$TARGET.qcow2 ]; then
  echo "$0: build/$TARGET.qcow2 already exists, not rebuilding"
  exit
fi

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

utils/addlayer.sh $1 $(dirname $0)
flatten_qcow2 build/$TARGET.qcow2
compress_qcow2 build/$TARGET.qcow2

echo \$ glance image-create --name $TARGET --file build/$TARGET.qcow2 --disk-format qcow2 --container-format bare --min-disk 10 --is-public True
