#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms
yum_install bash-completion control-center evince firefox gdm gnome-classic-session gnome-session gnome-terminal man nautilus tigervnc-server urw-fonts xinetd xorg-x11-drivers xorg-x11-xinit

ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target

cp monitors.xml /etc/gnome-settings-daemon/xrandr

sed -i -e '/^\[greeter\]/ a \
IncludeAll=false\
Include=demo
/^\[xdmcp\]/ a \
Enable=true' /etc/gdm/custom.conf

cp rfb /etc/xinetd.d

sed -i -e '/-A INPUT -i lo -j ACCEPT/ a\
-A INPUT -p tcp -m state --state NEW -m tcp --dport 5900 -j ACCEPT' /etc/sysconfig/iptables

cp 01-fixes /etc/dconf/db/local.d

dconf update

useradd demo
passwd -d demo
passwd -e demo
echo 'demo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

mkdir /home/demo/Desktop
for shortcut in firefox gnome-terminal; do
  install -m 0755 /usr/share/applications/$shortcut.desktop /home/demo/Desktop
done
echo Path=/home/demo >>/home/demo/Desktop/gnome-terminal.desktop
chown -R demo:demo /home/demo/Desktop

sed -i -e '/^#PermitEmptyPasswords/ a \
PermitEmptyPasswords yes' /etc/ssh/sshd_config

for dest in password-auth system-auth; do
  cp pam-auth-demobuilder /etc/pam.d/$dest-demobuilder
  ln -sf $dest-demobuilder /etc/pam.d/$dest
done

sed -i -e '/load-module.*bluetooth/ s/^/#/' /etc/pulse/default.pa

sed -i -e '/dateMenu\|volume/ s!^!//!' /usr/share/gnome-shell/js/ui/panel.js
