#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms
yum_install bash-completion evince firefox gdm gnome-classic-session gnome-session gnome-terminal man nautilus system-config-firewall-base tigervnc-server urw-fonts xinetd xorg-x11-drivers xorg-x11-xinit

ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target

cat >/etc/gnome-settings-daemon/xrandr/monitors.xml <<EOF
<monitors version="1">
  <configuration>
      <clone>no</clone>
      <output name="default">
          <vendor>???</vendor>
          <product>0x0000</product>
          <serial>0x00000000</serial>
          <width>1024</width>
          <height>768</height>
          <rate>60</rate>
          <x>0</x>
          <y>0</y>
          <rotation>normal</rotation>
          <reflect_x>no</reflect_x>
          <reflect_y>no</reflect_y>
          <primary>yes</primary>
      </output>
  </configuration>
</monitors>
EOF

sed -i -e '/^\[greeter\]/ a \
IncludeAll=false\
Include=demo
/^\[xdmcp\]/ a \
Enable=true' /etc/gdm/custom.conf

cat >/etc/xinetd.d/rfb <<EOF
service rfb
{
        protocol = tcp
        wait = no
        user = nobody
        server = /usr/bin/Xvnc
        server_args = -inetd -query localhost -once -SecurityTypes None
}
EOF

firewall-cmd --permanent --zone=public --add-port=5900/tcp

cat >/etc/dconf/db/local.d/01-fixes <<EOF
[org/gnome/settings-daemon/plugins/xrandr]
default-monitors-setup='do-nothing'

[org/gnome/desktop/session]
idle-delay=uint32 0

[org/gnome/desktop/wm/preferences]
num-workspaces=1
EOF

dconf update

mkdir /etc/skel/Desktop
for shortcut in firefox gnome-terminal; do
  cp /usr/share/applications/$shortcut.desktop /etc/skel/Desktop
  chmod 0755 /etc/skel/Desktop/$shortcut.desktop
done

useradd demo
passwd -d demo
passwd -e demo
echo 'demo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

sed -i -e '/^#PermitEmptyPasswords/ a \
PermitEmptyPasswords yes' /etc/ssh/sshd_config

for dest in password-auth system-auth; do
  cp pam-auth-demobuilder /etc/pam.d/$dest-demobuilder
  ln -sf $dest-demobuilder /etc/pam.d/$dest
done

cleanup
