#!/bin/bash -ex

. vm-functions

for image in \
    docker.io/openshift/hello-openshift:latest \
    docker.io/openshift/postgresql-92-centos7:latest \
    docker.io/openshift/mongodb-24-centos7:latest \
    docker.io/openshift/mysql-55-centos7:latest \
    registry.access.redhat.com/jboss-amq-6/amq-openshift:latest \
    registry.access.redhat.com/jboss-eap-6/eap-openshift:latest \
    registry.access.redhat.com/jboss-webserver-3/tomcat7-openshift:latest \
    registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift:latest \
    registry.access.redhat.com/openshift3/mongodb-24-rhel7:latest \
    registry.access.redhat.com/openshift3/mysql-55-rhel7:latest \
    registry.access.redhat.com/openshift3/nodejs-010-rhel7:latest \
    registry.access.redhat.com/openshift3/perl-516-rhel7:latest \
    registry.access.redhat.com/openshift3/php-55-rhel7:latest \
    registry.access.redhat.com/openshift3/postgresql-92-rhel7:latest \
    registry.access.redhat.com/openshift3/python-33-rhel7:latest \
    registry.access.redhat.com/openshift3/ruby-20-rhel7:latest \
    ; do
  docker_pull $image
done

systemctl stop openshift-node.service
oc delete pods --all
docker ps -aq | xargs docker rm -f
