#!/bin/bash -e

. utils/functions

if [ -z "$HTTPLISTENER" -o -z "$BRIDGE" -o ! -e keys/demobuilder.pub ]; then
  echo "$0: build environment incorrect"
  exit 1
fi

TARGET=build/$(basename $(dirname $0)).qcow2
if [ -e $TARGET ]; then
  echo "$0: $TARGET already exists, not rebuilding"
  exit
fi

TEMPDIR=$(mktemp -d)

ISO=$(cache https://download.eng.rdu2.redhat.com/released/RHEL-6/6.5/Server/x86_64/iso/RHEL6.5-20131111.0-Server-x86_64-DVD1.iso)

for FILE in initrd.img vmlinuz; do
  iso-read -i $ISO -e isolinux/$FILE -o $TEMPDIR/$FILE
done

qemu-img create -q -f qcow2 $TARGET 10G
qemu-kvm -nodefaults \
  -smp 2 \
  -m 2048 \
  -kernel $TEMPDIR/vmlinuz \
  -initrd $TEMPDIR/initrd.img \
  -append "ks=http://$HTTPLISTENER/$(dirname $0)/rhel-server-6.5.ks listener=$HTTPLISTENER" \
  -device virtio-scsi-pci \
  -drive discard=unmap,file=build/rhel-server-6.5.qcow2,id=disk1,if=none \
  -device scsi-disk,drive=disk1 \
  -net bridge,br=$BRIDGE \
  -net nic,model=virtio,macaddr=$(utils/random-mac.py) \
  -cdrom $ISO \
  -device vmware-svga \
  -vnc :0 \
  -usbdevice tablet

rm -rf $TEMPDIR

compress_qcow2 $TARGET
