#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms rhel-7-server-extras-rpms rhel-7-server-optional-rpms rhel-server-7-ose-beta-rpms

rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta

yum_install bind-utils bridge-utils docker git httpd-tools iptables-services lsof openshift-sdn-master openshift-sdn-node python-requests net-tools nmap-ncat PyYAML strace tcpdump wget yum-utils
yum_remove 'NetworkManager*'

sed -i -e 's!^OPTIONS=.*!OPTIONS='\''--selinux-enabled --insecure-registry 0.0.0.0/0'\''!' /etc/sysconfig/docker

systemctl enable docker

systemctl start docker

for image in \
	registry.access.redhat.com/openshift3_beta/mysql-55-rhel7 \
	registry.access.redhat.com/openshift3_beta/ose-deployer:v0.4.3.2 \
	registry.access.redhat.com/openshift3_beta/ose-docker-builder:v0.4.3.2 \
	registry.access.redhat.com/openshift3_beta/ose-docker-registry:v0.4.3.2 \
	registry.access.redhat.com/openshift3_beta/ose-haproxy-router:v0.4.3.2 \
	registry.access.redhat.com/openshift3_beta/ose-pod:v0.4.3.2 \
	registry.access.redhat.com/openshift3_beta/ose-sti-builder:v0.4.3.2 \
	registry.access.redhat.com/openshift3_beta/ruby-20-rhel7 \
	registry.access.redhat.com/openshift3_beta/sti-basicauthurl \
	docker.io/openshift/hello-openshift \
	docker.io/openshift/wildfly-8-centos \
	docker.io/fabric8/hawtio-kubernetes \
	mysql; do
  if ! curl -s $DCLISTENER/$image | gunzip 2>/dev/null | docker load &>/dev/null; then
    docker pull $image
    docker save $image | gzip | curl -s --data-binary @- $DCLISTENER/$image
  fi
done 

systemctl stop docker

yum_install http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
yum_install https://kojipkgs.fedoraproject.org//packages/ansible/1.8.4/1.el7/noarch/ansible-1.8.4-1.el7.noarch.rpm
yum_remove epel-release-7-5

cleanup
