#!/bin/bash -e

. utils/functions

TARGET=$1:$(basename $(dirname $0))

. targets/$TARGET
export MEM=${MEM:-1024}
export NAME=${NAME:-$TARGET}
export CPUS=${CPUS:-1}

if [ -e build/vsphere/$TARGET.ova ]; then
  echo "$0: build/vsphere/$TARGET.ova already exists, not rebuilding"
  exit
fi

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

utils/addlayer.sh $1 $(dirname $0)
mv build/$TARGET.qcow2 tmp/$TARGET.qcow2  # TODO
convert_qcow2 tmp/$TARGET.qcow2 raw
utils/VMDKstream.py tmp/$TARGET.raw tmp/$TARGET.vmdk

TMPDIR=$(mktemp -d)
envsubst <$(dirname $0)/template.ovf >$TMPDIR/template.ovf

tar -Pcf tmp/$TARGET.ova --transform='s!.*/!!' --transform="s/$TARGET.vmdk/template-disk1.vmdk/" $TMPDIR/template.ovf tmp/$TARGET.vmdk
rm -rf tmp/$TARGET.qcow2 tmp/$TARGET.raw tmp/$TARGET.vmdk $TMPDIR
mkdir build/vsphere
mv tmp/$TARGET.ova build/vsphere/$TARGET.ova
