#!/bin/bash -e

. utils/functions

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

BASE=$1
TARGET=$(basename $(dirname $0))

read_properties $BASE $TARGET

export BASE

if [ -e releases/$BASE:$TARGET.ova ]; then
  echo "$0: releases/$BASE:$TARGET.ova already exists, not rebuilding"
  exit
fi

utils/addlayer.sh build/$BASE.qcow2 targets/$TARGET tmp/$BASE:$TARGET.qcow2
convert_qcow2 tmp/$BASE:$TARGET.qcow2 raw

utils/VMDKstream.py tmp/$BASE:$TARGET.raw tmp/$BASE:$TARGET.vmdk

TMPDIR=$(mktemp -d)
envsubst <targets/$TARGET/template.ovf >$TMPDIR/template.ovf

tar -Pcf tmp/$BASE:$TARGET.ova --transform='s!.*/!!' --transform="s/$BASE:$TARGET.vmdk/template-disk1.vmdk/" $TMPDIR/template.ovf tmp/$BASE:$TARGET.vmdk
rm -rf tmp/$BASE:$TARGET.qcow2 tmp/$BASE:$TARGET.raw tmp/$BASE:$TARGET.vmdk $TMPDIR

mv tmp/$BASE:$TARGET.ova releases/$BASE:$TARGET.ova
