#!/bin/bash -e

. utils/functions

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

BASE=$1
TARGET=$(basename $(dirname $0))

read_config $BASE $TARGET

utils/addlayer.sh build/$BASE.qcow2 targets/$TARGET tmp/$BASE:$TARGET.qcow2
convert_qcow2 tmp/$BASE:$TARGET.qcow2 qcow2
compress_qcow2 tmp/$BASE:$TARGET.qcow2

mv tmp/$BASE:$TARGET.qcow2 releases/$BASE:$TARGET.qcow2

echo \$ glance image-create --name $BASE --file releases/$BASE:$TARGET.qcow2 --disk-format qcow2 --container-format bare --min-disk $LAYER_DISK --is-public True
