#!/bin/bash -ex

. vm-functions

cat <<'EOF' >/etc/rc.d/rc.local
#!/bin/bash

HOSTNAME=$(hostname)
IP=$(ip addr show dev eth0 | sed -n '/inet / { s!.*inet !!; s!/.*!!; p; }')

sed -i -e "s/^OPTIONS=.*/OPTIONS=\"--loglevel=4 --public-master=$HOSTNAME\"/" /etc/sysconfig/openshift-master

sed -i -e 's/^OPTIONS=.*/OPTIONS="--loglevel=4"/' /etc/sysconfig/openshift-node

sed -i -e 's/^OPTIONS=.*/OPTIONS="-v=4"/' /etc/sysconfig/openshift-sdn-master

sed -i -e "s!^MASTER_URL=.*!MASTER_URL=\"http://ose3-allinone.example.com:4001\"!; s!^OPTIONS=.*!OPTIONS=\"-v=4\"!; s!^DOCKER_OPTIONS=.*!DOCKER_OPTIONS=\"--insecure-registry=0.0.0.0/0 -b=lbr0 --mtu=1450 --selinux-enabled\"!" /etc/sysconfig/openshift-sdn-node

sed -i -e "s!^MINION_IP=.*!MINION_IP=\"$IP\"!" /etc/sysconfig/openshift-sdn-node

sed -i -e "/$HOSTNAME/ d;" /etc/hosts
echo "$IP $HOSTNAME" >>/etc/hosts

systemctl start openshift-master
sleep 10
systemctl start openshift-sdn-master
systemctl start openshift-sdn-node
EOF

chmod 0755 /etc/rc.d/rc.local

echo ose3-allinone.example.com >/etc/hostname

cleanup
