#!/bin/bash -e

. utils/functions

TARGET=$1:$(basename $(dirname $0))

. targets/$TARGET
export MEM=${MEM:-1024}
export NAME=${NAME:-$TARGET}
export CPUS=${CPUS:-1}

if [ -e build/$TARGET.ova ]; then
  echo "$0: build/$TARGET.ova already exists, not rebuilding"
  exit
fi

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

utils/addlayer.sh $1 $(dirname $0)
mv build/$TARGET.qcow2 tmp/$TARGET.qcow2  # TODO
convert_qcow2 tmp/$TARGET.qcow2 vmdk

TMPDIR=$(mktemp -d)
envsubst <$(dirname $0)/template.ovf >$TMPDIR/template.ovf

tar -Pczf tmp/$TARGET.ova --transform='s!.*/!!' --transform="s/$TARGET.vmdk/template-disk1.vmdk/" $TMPDIR/* tmp/$TARGET.vmdk
rm -rf tmp/$TARGET.qcow2 tmp/$TARGET.vmdk $TMPDIR
mv tmp/$TARGET.ova build/$TARGET.ova
