#!/bin/bash -e

. utils/functions

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

BASE=$1
TARGET=$(basename $(dirname $0))

read_config $BASE $TARGET

utils/addlayer.sh build/$BASE.qcow2 targets/$TARGET tmp/$BASE:$TARGET.qcow2
convert_qcow2 tmp/$BASE:$TARGET.qcow2 qcow2
compress_qcow2 tmp/$BASE:$TARGET.qcow2
# ~/src/vmdisktool/vmdisktool -f qcow2 tmp/$BASE:$TARGET.qcow2 tmp/$BASE:$TARGET.qcow2.tmp
# mv tmp/$BASE:$TARGET.qcow2.tmp tmp/$BASE:$TARGET.qcow2

TMPDIR=$(mktemp -d)
envsubst <targets/$TARGET/Vagrantfile >$TMPDIR/Vagrantfile
envsubst <targets/$TARGET/metadata.json >$TMPDIR/metadata.json

tar -c --transform='s!.*/!!' --transform="s/$BASE:$TARGET.qcow2/box.img/" $TMPDIR/metadata.json tmp/$BASE:$TARGET.qcow2 $TMPDIR/Vagrantfile | pigz >tmp/$BASE:$TARGET.box
rm -rf tmp/$BASE:$TARGET.qcow2 $TMPDIR

mv tmp/$BASE:$TARGET.box releases/$BASE:$TARGET.box

echo \$ vagrant box add $BASE releases/$BASE:$TARGET.box
echo \$ vagrant init $BASE
echo \$ vagrant up
