Vagrant::Config.run("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = $MEM
    libvirt.cpus = $CPUS
  end
end

include_vagrantfile = File.expand_path("../include/_Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
