#!/bin/bash

cp /usr/local/sti/_assemble /tmp/assemble
if [ -n "$ca_cert" ]; then
  echo "$ca_cert" >>/tmp/ca_cert
  sed -i -e 's!pip install!pip install --cert /tmp/ca_cert!' /tmp/assemble
fi

exec /tmp/assemble "$@"
