#!/bin/bash -ex

. vm-functions

register_channels
yum_install bash-completion control-center evince firefox gdm gnome-session gnome-terminal nautilus tigervnc-server xinetd xorg-x11-drivers xorg-x11-server-Xorg

useradd demo
passwd -d demo
passwd -e demo
echo 'demo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

sed -i -e '/^#PermitEmptyPasswords/ a \
PermitEmptyPasswords yes' /etc/ssh/sshd_config

sed -i -e '/^\[greeter\]/ a \
IncludeAll=false\
Include=demo
/^\[xdmcp\]/ a \
Enable=true\
PingIntervalSeconds=0' /etc/gdm/custom.conf

cp rfb /etc/xinetd.d

mkdir -p /var/lib/gdm/.config
cp monitors.xml /var/lib/gdm/.config
chown -R gdm:gdm /var/lib/gdm

mkdir /home/demo/.config
cp /var/lib/gdm/.config/monitors.xml /home/demo/.config/monitors.xml
chown -R demo:demo /home/demo/.config

cp user /etc/dconf/profile

mkdir /etc/dconf/db/local.d
cp 01-fixes /etc/dconf/db/local.d

dconf update

cp 80-color-manager.rules /etc/polkit-1/rules.d

sed -i -e '/-A INPUT -i lo -j ACCEPT/ a\
-A INPUT -p tcp -m state --state NEW -m tcp --dport 5900 -j ACCEPT' /etc/sysconfig/iptables

ln -sf /lib/systemd/system/graphical.target /etc/systemd/system/default.target
