#!/bin/bash -ex

. vm-functions

openshift_install() {
  https_proxy=$PROXY curl -so openshift.sh https://raw.githubusercontent.com/openshift/openshift-extras/enterprise-2.2/enterprise/install-scripts/generic/openshift.sh
  chmod 0755 ./openshift.sh
  ./openshift.sh
}

openshift_enable_admin_console() {
  sed -i -e '/ProxyPassReverse \/console/ a\
ProxyPass /admin-console http://127.0.0.1:8080/admin-console' /etc/httpd/conf.d/000002_openshift_origin_broker_proxy.conf
  sed -i -e '/ProxyPassReverse \/console/ a\
ProxyPass /assets http://127.0.0.1:8080/assets' /etc/httpd/conf.d/000002_openshift_origin_broker_proxy.conf

  service httpd reload
}

openshift_configure_node() {
  sed -i -e 's/^cpu_cfs_quota_us=.*/cpu_cfs_quota_us=-1/' /etc/openshift/resource_limits.conf
  service ruby193-mcollective restart
}

jbds_install() {
  https_proxy=$PROXY curl -so jbdevstudio.jar https://download.eng.rdu2.redhat.com/released/jbdevstudio/7.1.1/jbdevstudio-product-universal-7.1.1.GA-v20140314-2145-B688.jar
  java -jar jbdevstudio.jar jbds.xml
}

nexus_install() {
  ( cd /usr/local && https_proxy=$PROXY curl -Ls https://download.sonatype.com/nexus/oss/nexus-2.11.1-01-bundle.tar.gz | tar -xz )

  RUN_AS_USER=root /usr/local/nexus-*/bin/nexus start
  RUN_AS_USER=root /usr/local/nexus-*/bin/nexus stop

  echo RUN_AS_USER=root /usr/local/nexus-*/bin/nexus start >>/etc/rc.local
}

firefox_set_homepage() {
  cat >/usr/lib64/firefox/browser/defaults/preferences/local-settings.js <<EOF
pref("general.config.filename", "firefox.cfg");
pref("general.config.obscure_value", 0);
pref("startup.homepage_override_url", "");
pref("startup.homepage_welcome_url", "");
EOF

  cat >/usr/lib64/firefox/firefox.cfg <<EOF
//
pref("browser.startup.homepage", "$1");
EOF
}

export CONF_ACTIONS=do_all_actions,post_deploy
export CONF_BROKER_HOSTNAME=openshift.example.com
export CONF_BROKER_IP_ADDR=127.0.0.1
export CONF_NAMED_ENTRIES=openshift:127.0.0.1,activemq:127.0.0.1,datastore:127.0.0.1
export CONF_NAMED_IP_ADDR=127.0.0.1
export CONF_NO_NTP=true
export CONF_NODE_IP_ADDR=127.0.0.1
export CONF_OPENSHIFT_PASSWORD1=redhat

register_channels jb-eap-6-for-rhel-6-server-rpms jb-ews-2-for-rhel-6-server-rpms rhel-6-server-ose-2.2-infra-rpms rhel-6-server-ose-2.2-jbossamq-rpms rhel-6-server-ose-2.2-jbosseap-rpms rhel-6-server-ose-2.2-jbossfuse-rpms rhel-6-server-ose-2.2-node-rpms rhel-6-server-ose-2.2-rhc-rpms rhel-6-server-rpms rhel-server-rhscl-6-rpms

yum_remove rsyslog

register_https_proxy_ca

openshift_install
openshift_enable_admin_console
openshift_configure_node

create_ca
sign_cert /etc/pki/tls/private/localhost.key '*.example.com' /etc/pki/tls/certs/localhost.crt
service httpd reload

curl -u demo:$CONF_OPENSHIFT_PASSWORD1 https://$CONF_BROKER_HOSTNAME/console/applications &>/dev/null
oo-admin-ctl-domain -l demo -c create -n demo

cp demouser.sh /home/demo
su demo -c 'cd; ./demouser.sh; rm demouser.sh'

jbds_install
nexus_install

firefox_set_homepage https://$CONF_BROKER_HOSTNAME/

# nexus configuration and .m2 etc
# add apps
# add docs

cleanup
