#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms rhel-7-server-optional-rpms rhel-server-rhscl-7-rpms

yum_install maven30

for image in \
    docker.io/openshift/hello-openshift:latest \
    ; do
  docker_pull $image
done

mkdir -p /home/demo/.m2
cp settings.xml /home/demo/.m2
sed -i -e "/<proxies>/ a \
<proxy><host>$HOSTNAME</host></proxy>" /home/demo/.m2/settings.xml

http_proxy=http://$HOSTNAME:8080/ curl -so /etc/pki/ca-trust/source/anchors/ca-webproxycache.crt http://cacert/
update-ca-trust

https_proxy=$PROXY curl -sLO https://download.eng.rdu2.redhat.com/released/jbdevstudio/8.1.0/jboss-devstudio-8.1.0.GA-installer-standalone.jar
java -jar jboss-devstudio-8.1.0.GA-installer-standalone.jar InstallConfigRecord.xml
cp 'Red Hat JBoss Developer Studio 8.1.0.GA.desktop' /usr/share/applications
install -m 0755 -o demo 'Red Hat JBoss Developer Studio 8.1.0.GA.desktop' /home/demo/Desktop

https_proxy=$PROXY curl -sLO https://github.com/jim-minter/eclipse-importer/raw/master/com.redhat.importer_1.0.0.201509031446.jar
mv com.redhat.importer_1.0.0.201509031446.jar /usr/local/jbdevstudio/studio/plugins/

yum_install xorg-x11-server-Xvfb

COMMIT=c76cebc764112fcc0493855fa5983ce5ffe44508
https_proxy=$PROXY curl -sLO https://github.com/jim-minter/ose3-demos/archive/$COMMIT.zip
unzip -q $COMMIT.zip
mv ose3-demos-$COMMIT/* /home/demo
chown -R demo:demo /home/demo

for i in /home/demo/git/*; do
  git init --bare /var/lib/git/demo/$(basename $i)
  chown -R nobody:nobody /var/lib/git

  pushd $i
  git init
  git add -A
  git commit -m 'Initial commit'
  git remote add origin git://$HOSTNAME/demo/$(basename $i)
  git push -u origin master

  chown -R demo:demo $i

  if [ -e pom.xml ]; then
    BUILD="$BUILD $(basename $i) $i"
    su - demo -c "scl enable maven30 'cd $i && mvn clean package'"
    rm -rf target
  fi

  popd

  cat >/var/lib/git/demo/$(basename $i)/hooks/post-receive <<EOF
#!/bin/bash

echo 'Triggering OSE3 build...'
curl -sX POST 'https://$HOSTNAME:8443/osapi/v1beta3/namespaces/demo/buildconfigs/$(basename $i)/webhooks/secret/generic'
EOF
  chmod 0755 /var/lib/git/demo/$(basename $i)/hooks/post-receive
  chown -R nobody:nobody /var/lib/git
done

oc create -f /home/demo/git/monster/openshift/ticket-monster-template.yaml -n openshift

su - demo -c "xvfb-run /usr/local/jbdevstudio/jbdevstudio -data workspace $BUILD"

yum -y history undo $(yum history list | grep -A1 ^- | tail -1 | awk '{print $1;}')
rm /usr/local/jbdevstudio/studio/plugins/com.redhat.importer_1.0.0.201509031446.jar

chown -R demo:demo /home/demo

for i in $(echo 'SELECT url FROM cache WHERE url LIKE "%.sha1";' | sqlite3 /var/cache/webproxycache/webproxycache.db); do
  http_proxy=http://$HOSTNAME:8080/ https_proxy=http://$HOSTNAME:8080/ curl -so /dev/null $(echo $i | sed -e 's/.sha1$//').md5
done
