#!/bin/bash -x

. utils/functions

if [ $# -ne 2 ]; then
  echo "usage: $0 in.qcow2 out.box"
  exit 1
fi

flatten_qcow2 $1

IN=$(realpath $1)
OUT=$(realpath $2)

pushd $(dirname $0)
ln $IN box-disk1.img
tar cvzf $OUT metadata.json Vagrantfile box.xml box-disk1.img
rm box-disk1.img
popd

echo \$ vagrant box add $(basename $2 .box) $2
echo \$ vagrant init $(basename $2 .box)
echo \$ vagrant up