Vagrant.configure("2") do |config|
  config.vm.box = "$NAME"

  config.vm.define :test_vm do |test_vm|
    test_vm.vm.network :bridged, :adapter => 1
  end

  config.vm.provider :libvirt do |domain|
    domain.memory = $MEM
    domain.cpus = $CPUS
  end
end
