#!/bin/bash -e

. utils/functions

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

BASE=$1
TARGET=$(basename $(dirname $0))

if ! needs_build releases/$BASE:$TARGET.box $(dirname $0) build/$BASE.qcow2; then
  exit 0
fi

read_config $BASE $TARGET

utils/addlayer.sh build/$BASE.qcow2 targets/$TARGET tmp/$BASE:$TARGET.qcow2
convert_qcow2 tmp/$BASE:$TARGET.qcow2 vmdk

TMPDIR=$(mktemp -d)
export LAYER_DISK_BYTES=$(($LAYER_DISK * 2**30))
envsubst <targets/$TARGET/box.ovf >$TMPDIR/box.ovf

tar -c --transform='s!.*/!!' --transform="s/$BASE:$TARGET.vmdk/box-disk1.vmdk/" targets/$TARGET/metadata.json tmp/$BASE:$TARGET.vmdk targets/$TARGET/Vagrantfile $TMPDIR/box.ovf | nice pigz >tmp/$BASE:$TARGET.box
rm -rf tmp/$BASE:$TARGET.qcow2 tmp/$BASE:$TARGET.vmdk $TMPDIR

mv tmp/$BASE:$TARGET.box releases/$BASE:$TARGET.box

echo \$ vagrant box add $BASE:$TARGET releases/$BASE:$TARGET.box
echo \$ vagrant init $BASE:$TARGET
echo \$ vagrant up
