Vagrant::Config.run("2") do |config|
  config.vm.base_mac = "080027129698"
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.gui = true
  end
end

include_vagrantfile = File.expand_path("../include/_Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
