#!/bin/bash -ex

. vm-functions

register_channels rhel-6-server-rpms
yum_install bash-completion control-center evince firefox gdm gnome-panel gnome-session gnome-terminal man nautilus system-config-firewall-base tigervnc-server urw-fonts xinetd xorg-x11-drivers xorg-x11-xinit

useradd demo
passwd -d demo
passwd -e demo
echo 'demo ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers

sed -i -e '/^#PermitEmptyPasswords/ a \
PermitEmptyPasswords yes' /etc/ssh/sshd_config

su demo -c 'gconftool-2 --type int --set /apps/metacity/general/num_workspaces 1'

sed -i -e '/^\[greeter\]/ a \
IncludeAll=false\
Include=demo
/^\[xdmcp\]/ a \
Enable=true' /etc/gdm/custom.conf

cp vnc-server /etc/xinetd.d

lokkit -p 22:tcp
lokkit -p 5900:tcp

sed -i -e 's/id:3:initdefault:/id:5:initdefault:/' /etc/inittab
