#!/bin/bash -e

. config

interface_ip() {
  ip addr show dev $1 | sed -n '/inet / { s!.*inet !!; s!/.*!!; p; }'
}

apiserver_start() {
  eval $(utils/apiserver.py $(interface_ip $BRIDGE))
  export APILISTENER
}

apiserver_stop() {
  kill $APIPID
}

compress_qcow2() {
  BACKINGFILE=$(qemu-img info $1 | sed -n -e '/^backing file: / { s/.*: //; p; }')

  if [ -z $BACKINGFILE ]; then
    qemu-img convert -c -O qcow2 $1 $1.tmp
  else
    qemu-img convert -c -O qcow2 -B $BACKINGFILE $1 $1.tmp
  fi

  mv $1.tmp $1
}

convert_qcow2() {
  qemu-img convert -O $2 $1 $1.tmp
  mv $1.tmp $(echo $1 | sed -e 's/\.[^.]*$//').$2
}

wait_pid() {
  while [ -e /proc/$1 ]; do
    sleep 1
  done
}

if [ "$DEBUG" ]; then
  set -x
fi
