#!/bin/bash

. config

cache() {
  DEST=cache/$(echo $1 | sed -e 's!.*://!!')
  if ! [ -e $DEST ]; then
    mkdir -p $(dirname $DEST)
    curl -o $DEST $1
  fi
  echo $DEST
}

interface_ip() {
  ifconfig $1 | awk '/inet / { print $2; }'
}

proxy_start() {
  eval $(utils/yumproxy.py $(interface_ip $BRIDGE))
  export PROXYLISTENER
}

proxy_stop() {
  kill $PROXYPID
}

httpserver_start() {
  eval $(utils/httpserver.py $(interface_ip $BRIDGE))
  export HTTPLISTENER
}

httpserver_stop() {
  kill $HTTPPID
}

compress_qcow2() {
  BACKINGFILE=$(qemu-img info $1 | sed -n -e '/^backing file: / { s/.*: //; p; }')

  if [ -z $BACKINGFILE ]; then
    qemu-img convert -cp -O qcow2 $1 $1.tmp
    mv $1.tmp $1

  else
    qemu-img convert -cp -O qcow2 -B $BACKINGFILE $1 $1.tmp
    mv $1.tmp $1
  fi
}

flatten_qcow2() {
  qemu-img convert -cp -O qcow2 $1 $1.tmp
  mv $1.tmp $1
}

wait_pid() {
  while [ -e /proc/$1 ]; do
    sleep 1
  done
}
