#!/bin/bash -ex

cd demobuilder

. vm-functions

if ! [ -e /usr/local/bin/demobuilder-cleanup.sh ]; then
  echo '#!/bin/bash -x' >/usr/local/bin/demobuilder-cleanup.sh
  chmod 0755 /usr/local/bin/demobuilder-cleanup.sh
fi

if ! ./install; then
  if [ -n "$RHN_USER" -a -x /sbin/subscription-manager -a -e /etc/pki/consumer/cert.pem ]; then
    subscription-manager unregister
  fi

  echo "$0: FAILED."
  exit 1
fi

cd ..
rm -rf demobuilder

cleanup

echo "$0: Done."
( sleep 1; poweroff ) </dev/null &>/dev/null &
