#!/bin/bash -e

. utils/functions

TARGET=$(basename $(dirname $0))
if [ -e build/$TARGET.qcow2 ]; then
  echo "$0: build/$TARGET.qcow2 already exists, not rebuilding"
  exit
fi

QCOW=$(cache $MIRROR_RHN/content/dist/rhel/server/6/6Server/x86_64/iso/rhel-guest-image-6.6-20141222.0.x86_64.qcow2)

cp $QCOW tmp/$TARGET.qcow2

guestfish --rw -a tmp/$TARGET.qcow2 -i <<EOF
mkdir /root/.ssh
chmod 0700 /root/.ssh
copy-in keys/demobuilder.pub /root/.ssh
mv /root/.ssh/demobuilder.pub /root/.ssh/authorized_keys
chown 0 0 /root/.ssh/authorized_keys
sh "chcon system_u:object_r:ssh_home_t:s0 /root/.ssh /root/.ssh/authorized_keys"
mv /etc/rc.d/rc3.d/S50cloud-init-local /etc/rc.d/rc3.d/K50cloud-init-local
mv /etc/rc.d/rc3.d/S51cloud-init /etc/rc.d/rc3.d/K50cloud-init
mv /etc/rc.d/rc3.d/S52cloud-config /etc/rc.d/rc3.d/K50cloud-config
mv /etc/rc.d/rc3.d/S53cloud-final /etc/rc.d/rc3.d/K50cloud-final
EOF

mv tmp/$TARGET.qcow2 build/$TARGET.qcow2
