#!/bin/bash -x

. vm-functions

register_channels rhel-x86_64-server-6
install_packages nfs-utils nfs-utils-lib

useradd vagrant
echo vagrant | passwd --stdin vagrant
echo 'vagrant ALL=(ALL) NOPASSWD: ALL' >>/etc/sudoers
passwd -l root

sed -i -e '/Defaults.*requiretty/ d;' /etc/sudoers

su vagrant -c 'mkdir -m 0700 /home/vagrant/.ssh; curl -so /home/vagrant/.ssh/authorized_keys https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub; chmod 0600 /home/vagrant/.ssh/authorized_keys'

cleanup
