#!/bin/bash -e

. utils/functions

TARGET=$1:$(basename $(dirname $0))

. targets/$TARGET
export MEM=${MEM:-1024}
export NAME=${NAME:-vagrant}
export CPUS=${CPUS:-1}

if [ -e build/$TARGET.box ]; then
  echo "$0: build/$TARGET.box already exists, not rebuilding"
  exit
fi

if [ $# -ne 1 ]; then
  echo "usage: $0 base"
  exit 1
fi

rm -f build/$TARGET.qcow2
utils/addlayer.sh $1 $(dirname $0)
flatten_qcow2 build/$TARGET.qcow2

TMPDIR=$(mktemp -d)
envsubst <$(dirname $0)/box.xml >$TMPDIR/box.xml

tar czf build/$TARGET.box --transform='s!.*/!!' --transform="s/$TARGET.qcow2/box-disk1.img/" $(dirname $0)/{metadata.json,Vagrantfile} build/$TARGET.qcow2 $TMPDIR/box.xml
rm -f build/$TARGET.qcow2 $TMPDIR

echo \$ vagrant box add $TARGET build/$TARGET.box
echo \$ vagrant init $TARGET
echo \$ vagrant up
