#!/bin/bash -ex

. vm-functions

register_channels rhel-6-server-rpms
yum_install httpd mysql-server php system-config-firewall-base

mv index.php /var/www/html/
restorecon -Rv /var/www/html

chkconfig httpd on
lokkit -p 80:tcp

cleanup
