#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-beta-rpms rhel-7-server-extras-rpms rhel-server-7-ose-beta-rpms

rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta

yum_install bind-utils bridge-utils docker git iptables-services lsof python-requests net-tools '*openshift*' openvswitch strace tcpdump wget
yum_remove 'NetworkManager*'

sed -i -e 's!^OPTIONS=.*!OPTIONS=--insecure-registry 0.0.0.0/0 -H fd://!' /etc/sysconfig/docker

sed -i -e '/^-A INPUT -i lo -j ACCEPT/ a \
-A INPUT -p tcp -m state --state NEW -m tcp --dport 10250 -j ACCEPT \
-A INPUT -p tcp -m state --state NEW -m tcp --dport 8443:8444 -j ACCEPT \
-A INPUT -p tcp -m state --state NEW -m tcp --dport 7001 -j ACCEPT \
-A INPUT -p tcp -m state --state NEW -m tcp --dport 4001 -j ACCEPT \
-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT \
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT' /etc/sysconfig/iptables

systemctl disable firewalld
systemctl enable openvswitch
systemctl enable docker
systemctl enable iptables

cat <<EOF >>/root/.bash_profile
export KUBECONFIG=/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig
EOF

cp /etc/sysconfig/docker /etc/sysconfig/docker.bak
cat <<EOF >>/etc/sysconfig/docker
HTTP_PROXY=$PROXY
HTTPS_PROXY=$PROXY
EOF

register_https_proxy_ca

systemctl start docker

for image in \
	registry.access.redhat.com/openshift3_beta/ose-deployer \
	registry.access.redhat.com/openshift3_beta/ose-docker-builder \
	registry.access.redhat.com/openshift3_beta/ose-docker-registry \
	registry.access.redhat.com/openshift3_beta/ose-haproxy-router \
	registry.access.redhat.com/openshift3_beta/ose-pod \
	registry.access.redhat.com/openshift3_beta/ose-sti-builder \
	openshift/hello-openshift \
	openshift/ruby-20-centos7 \
    openshift/wildfly-8-centos \
    fabric8/hawtio-kubernetes \
	mysql; do
  docker pull $image
done 

systemctl stop docker
mv /etc/sysconfig/docker.bak /etc/sysconfig/docker

cleanup