#!/bin/bash 

. utils/functions

LAYER=${2:-$(dirname $0)}

DISKIMAGE="build/$1.qcow2"

echo "Will try and run disk image: $DISKIMAGE "

if [ -e "$DISKIMAGE" ]; then
	echo "That disk image exists, I will try and start it."

	qemu-kvm \
		-drive file=$DISKIMAGE \
		-net bridge,br=$BRIDGE \
		-net nic,model=virtio

else
	echo "Cannot run a nonexistant disk image!"
fi
