#!/bin/bash -e

. utils/functions

if [ ! -e keys/demobuilder.pub ]; then
  echo "$0: build environment incorrect"
  exit 1
fi

TARGET=build/$(basename $(dirname $0)).qcow2
if [ -e $TARGET ]; then
  echo "$0: $TARGET already exists, not rebuilding"
  exit
fi

QCOW=$(cache https://download.eng.rdu2.redhat.com/brewroot/packages/rhel-guest-image/6.5/20140603.0/images/rhel-guest-image-6.5-20140603.0.x86_64.qcow2)

cp $QCOW $TARGET

guestfish --rw -a $TARGET -i <<EOF
mkdir /root/.ssh
chmod 0700 /root/.ssh
copy-in keys/demobuilder.pub /root/.ssh
mv /root/.ssh/demobuilder.pub /root/.ssh/authorized_keys
chown 0 0 /root/.ssh/authorized_keys
sh "chcon system_u:object_r:ssh_home_t:s0 /root/.ssh /root/.ssh/authorized_keys"
rm /etc/rc.d/rc3.d/S50cloud-init-local
rm /etc/rc.d/rc3.d/S51cloud-init
rm /etc/rc.d/rc3.d/S52cloud-config
rm /etc/rc.d/rc3.d/S53cloud-final
EOF
