#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms rhel-7-server-rh-common-rpms
yum_install cloud-init

yum_install $MIRROR_FEDORA/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
sed -i -e "s!^#baseurl=http://download.fedoraproject.org/!baseurl=$MIRROR_FEDORA/!; s/^mirrorlist=/#mirrorlist=/" /etc/yum.repos.d/epel.repo
yum_install fio
yum_remove epel-release-7-5
rm /etc/yum.repos.d/epel.repo.rpmsave

systemctl enable cloud-init.service

cp 99_demobuilder.cfg /etc/cloud/cloud.cfg.d

cp fix-lib-modules.sh /usr/local/libexec
cp fix-lib-modules.service /lib/systemd/system
systemctl enable fix-lib-modules

grubby --update-kernel=ALL --remove-args=quiet

[ -e /home/demo ] && passwd -l demo
