#!/bin/bash -ex

. vm-functions

register_channels rhel-7-server-rpms rhel-7-server-rh-common-rpms
rpm -Uvh http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

yum_install cloud-init fio
rpm -e epel-release

systemctl enable cloud-init.service

cp 99_demobuilder.cfg /etc/cloud/cloud.cfg.d

cp fix-lib-modules.sh /usr/local/libexec
cp fix-lib-modules.service /lib/systemd/system
systemctl enable fix-lib-modules

grubby --update-kernel=ALL --remove-args=quiet

[ -e /home/demo ] && passwd -l demo
