#!/bin/bash -x

. vm-functions

if grep -q 'release 6' /etc/redhat-release; then
  register_channels rhel-x86_64-server-rh-common-6 rhel-x86_64-server-6
elif grep -q 'release 7' /etc/redhat-release; then
  register_channels rhel-x86_64-server-rh-common-7 rhel-x86_64-server-7
fi

yum_install cloud-init

rm /root/.ssh/authorized_keys

cleanup
